### ISSUE TITLE
Should stop using set-output command

### ISSUE THREAD

**Issue by Marcdsv** [tmelliottjr/extract-regex-action#2]
I'm getting a warning in my workflow when using this action because of the `set-output` command:
```
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

The [link in the warning message](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/) explains well how it must be replaced. The `set-output` and `set-state` commands will be disabled starting 1st June 2023.

**Comment by tmelliottjr** [comment]
The link you've shared indicates that the `setOutput` function is updated in `@actions/core` in version `v1.10.0` or greater which is what is being used [here](https://github.com/tmelliottjr/extract-regex-action/blob/main/package.json#L7) and [here](https://github.com/tmelliottjr/extract-regex-action/blob/main/index.ts#L42-L43).

Are you able to share your workflow / output?
